package com.zitech.appframework2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo {

    private Long id;
    private Integer role;
    private Integer userId;
    private Integer gender;
    private String account;
    private String password;
    private String loginName;
    private String loginPhone;
    private String name;
    private String nikeName;
    private String school;
    private String grade;
    private String userClass;
    private String birthday;
    private String bindQQ;
    private String bindPhone;
    private Boolean promiseState;

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, Integer role, Integer userId, Integer gender, String account, String password, String loginName, String loginPhone, String name, String nikeName, String school, String grade, String userClass, String birthday, String bindQQ, String bindPhone, Boolean promiseState) {
        this.id = id;
        this.role = role;
        this.userId = userId;
        this.gender = gender;
        this.account = account;
        this.password = password;
        this.loginName = loginName;
        this.loginPhone = loginPhone;
        this.name = name;
        this.nikeName = nikeName;
        this.school = school;
        this.grade = grade;
        this.userClass = userClass;
        this.birthday = birthday;
        this.bindQQ = bindQQ;
        this.bindPhone = bindPhone;
        this.promiseState = promiseState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRole() {
        return role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getLoginPhone() {
        return loginPhone;
    }

    public void setLoginPhone(String loginPhone) {
        this.loginPhone = loginPhone;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNikeName() {
        return nikeName;
    }

    public void setNikeName(String nikeName) {
        this.nikeName = nikeName;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    public String getUserClass() {
        return userClass;
    }

    public void setUserClass(String userClass) {
        this.userClass = userClass;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getBindQQ() {
        return bindQQ;
    }

    public void setBindQQ(String bindQQ) {
        this.bindQQ = bindQQ;
    }

    public String getBindPhone() {
        return bindPhone;
    }

    public void setBindPhone(String bindPhone) {
        this.bindPhone = bindPhone;
    }

    public Boolean getPromiseState() {
        return promiseState;
    }

    public void setPromiseState(Boolean promiseState) {
        this.promiseState = promiseState;
    }

    @Override
    public String toString() {
        return "UserInfo{" +
                "id=" + id +
                ", role=" + role +
                ", userId=" + userId +
                ", gender=" + gender +
                ", account='" + account + '\'' +
                ", password='" + password + '\'' +
                ", loginName='" + loginName + '\'' +
                ", loginPhone='" + loginPhone + '\'' +
                ", name='" + name + '\'' +
                ", nikeName='" + nikeName + '\'' +
                ", school='" + school + '\'' +
                ", grade='" + grade + '\'' +
                ", userClass='" + userClass + '\'' +
                ", birthday='" + birthday + '\'' +
                ", bindQQ='" + bindQQ + '\'' +
                ", bindPhone='" + bindPhone + '\'' +
                ", promiseState=" + promiseState +
                '}';
    }
}
